"use client";

import { useState } from "react";
import { ApiError, confirmFormNavigation, dateTime, items, useDirtyForm, useMutation, useResource, type Row } from "@/lib/api";
import { services, serviceName } from "@/lib/catalog";
import { localDateTime } from "@/lib/use-server-draft";
import { ButtonLink, Card, DataTable, ErrorState, Loading, MutationStatus, Notice, PageHeading } from "./ui";

export function EquipmentFields({ data }: { data: Row | null }) {
  return <><label>已配置設備／工具池<select name="equipment" required><option value="">選擇可用工具池</option>{items(data?.tools).filter(tool => tool.active).map(tool => <option key={tool.id} value={tool.name}>{tool.name} · 容量 {tool.capacity} · {(tool.service_codes || []).map(serviceName).join("、")}</option>)}</select></label><label>本次需要的工具單位<input name="equipment_units" type="number" required min={1} max={100} step={1} defaultValue={1} /></label></>;
}
export function DispatchNotice({ data }: { data: Row | null }) {
  return <Notice tone={data?.policy?.status === "unconfigured" ? "warning" : "info"}>{data?.policy?.travel_buffer_minutes == null ? "尚未核定交通緩衝政策，確認排程前須由 PM 完成配置。" : `交通緩衝政策 v${data.policy.version}：${data.policy.travel_buffer_minutes} 分鐘。`}伺服器會核對人員資格的有效期間、專案覆核政策、人員時段及工具容量；未配置項目不會推定可用。</Notice>;
}

export function DispatchPage() {
  const data = useResource("/internal/dispatch");
  const [page, setPage] = useState(1);
  const qualifications = useResource(`/internal/dispatch/qualifications?page=${page}&page_size=20`);
  const [qualification, setQualification] = useState<Row | null>(null);
  const [tool, setTool] = useState<Row | null>(null);
  const [dirty, setDirty] = useState(false);
  const policyAction = useMutation(); const qualificationAction = useMutation(); const toolAction = useMutation();
  useDirtyForm(dirty);
  function conflict(action: ReturnType<typeof useMutation>, reload: () => void) { return action.error instanceof ApiError && action.error.status === 409 ? <Notice tone="warning">目前設定已改變或存在預留，這次更新未套用。輸入仍保留，請重新讀取並核對最新版本。<button type="button" className="button button-secondary section-gap" onClick={reload}>重新讀取設定</button></Notice> : null; }
  return <><PageHeading title="派工資格、工具與政策" description="以實際核定的人員能力、時效與工具容量安排專案。開發設定僅為合成測試資料。" action={<ButtonLink href="/admin/projects">選擇專案排程</ButtonLink>} /><div className="section-stack">
    <Card title="人員與已核定能力">{data.loading ? <Loading /> : data.error ? <ErrorState error={data.error} retry={data.reload} /> : <><DispatchNotice data={data.data} /><DataTable rows={items(data.data)} title="派工人員" columns={[{ key: "name", title: "人員" }, { key: "roles", title: "角色", render: row => (row.roles || []).join("、") }, { key: "skills", title: "核定能力", render: row => (row.skills || []).map(serviceName).join("、") || "尚未配置" }, { key: "qualification_status", title: "資格狀態", render: row => row.qualification_status === "unconfigured" ? "尚未配置" : "依下方逐項資格" }]} /></>}</Card>
    {!data.loading && !data.error && <Card title="交通緩衝政策"><form key={data.data?.policy?.version || 0} className="form-stack" onChange={() => setDirty(true)} onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await policyAction.mutate("/internal/dispatch/policy", { expected_version: data.data?.policy?.version || 0, travel_buffer_minutes: Number(form.get("minutes")), reason: String(form.get("reason")).trim() })) { setDirty(false); data.reload(); } }}><label>每次派工交通緩衝（分鐘）<input name="minutes" type="number" required min={0} max={1440} step={1} defaultValue={data.data?.policy?.travel_buffer_minutes ?? ""} /></label><p className="form-help">0 分鐘也必須明確填寫並提供核定依據；不會自動套用預設值。</p><label>核定原因<textarea name="reason" required maxLength={1000} rows={3} /></label><button className="button" disabled={policyAction.pending}>確認核定緩衝政策</button>{conflict(policyAction, data.reload)}<MutationStatus action={policyAction} /></form></Card>}
    <Card title="逐項人員資格" aside={<button className="button button-small" onClick={() => { if (!confirmFormNavigation()) return; setQualification({}); setDirty(false); qualificationAction.clear(); }}>新增核定資格</button>}>
      {qualifications.loading ? <Loading /> : qualifications.error ? <ErrorState error={qualifications.error} retry={qualifications.reload} /> : <DataTable rows={items(qualifications.data)} title="派工資格" page={page} total={qualifications.data?.total} onPage={setPage} columns={[{ key: "user_id", title: "人員", render: row => items(data.data).find(person => person.id === row.user_id)?.name || row.user_id }, { key: "role", title: "職務", render: row => row.role === "engineer" ? "工程師" : "覆核者" }, { key: "service_code", title: "服務", render: row => serviceName(row.service_code) }, { key: "valid_until", title: "有效期限", render: row => row.valid_until ? dateTime(row.valid_until) : "未設定截止" }, { key: "active", title: "狀態", render: row => row.active ? "啟用" : "停用" }, { key: "edit", title: "管理", render: row => <button className="button button-secondary button-small" onClick={() => { if (!confirmFormNavigation()) return; setQualification(row); setDirty(false); qualificationAction.clear(); }}>編輯 v{row.version}</button> }]} />}
      {qualification && <form key={`${qualification.id || "new"}:${qualification.version || 0}`} className="form-stack section-gap" onChange={() => setDirty(true)} onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const expiry = String(form.get("valid_until") || ""); const result = await qualificationAction.mutate("/internal/dispatch/qualifications", { expected_version: qualification.version || 0, user_id: qualification.user_id || form.get("user_id"), role: qualification.role || form.get("role"), service_code: qualification.service_code || form.get("service_code"), valid_until: expiry ? new Date(expiry).toISOString() : null, active: form.get("active") === "on", reason: String(form.get("reason")).trim() }); if (result) { setQualification(result); setDirty(false); qualifications.reload(); data.reload(); } }}><div className="form-grid"><label>人員<select name="user_id" defaultValue={qualification.user_id || ""} disabled={!!qualification.id} required><option value="">選擇人員</option>{items(data.data).map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label>職務<select name="role" defaultValue={qualification.role || "engineer"} disabled={!!qualification.id}><option value="engineer">工程師</option><option value="reviewer">覆核者</option></select></label><label>服務<select name="service_code" defaultValue={qualification.service_code || "VA"} disabled={!!qualification.id}>{services.map(service => <option value={service.code} key={service.code}>{service.name}</option>)}</select></label><label>期限（裝置本地時間，選填）<input name="valid_until" type="datetime-local" defaultValue={localDateTime(qualification.valid_until)} /></label></div><label className="answer-option"><input name="active" type="checkbox" defaultChecked={qualification.active !== false} />啟用此人員、角色、服務資格</label><label>能力或變更依據<textarea name="reason" required maxLength={1000} rows={3} /></label><button className="button" disabled={qualificationAction.pending}>確認核定資格版本</button>{conflict(qualificationAction, qualifications.reload)}<MutationStatus action={qualificationAction} /></form>}
    </Card>
    <Card title="設備與工具容量" aside={<button className="button button-small" onClick={() => { if (!confirmFormNavigation()) return; setTool({}); setDirty(false); toolAction.clear(); }}>新增工具池</button>}><DataTable rows={items(data.data?.tools)} title="工具池" columns={[{ key: "name", title: "工具池" }, { key: "capacity", title: "同時可用單位" }, { key: "service_codes", title: "允許服務", render: row => (row.service_codes || []).map(serviceName).join("、") }, { key: "active", title: "狀態", render: row => row.active ? "啟用" : "停用" }, { key: "edit", title: "管理", render: row => <button className="button button-secondary button-small" onClick={() => { if (!confirmFormNavigation()) return; setTool(row); setDirty(false); toolAction.clear(); }}>編輯 v{row.version}</button> }]} />
      {tool && <form key={`${tool.id || "new"}:${tool.version || 0}`} className="form-stack section-gap" onChange={() => setDirty(true)} onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await toolAction.mutate("/internal/dispatch/tools", { expected_version: tool.version || 0, name: tool.name || String(form.get("name")).trim(), capacity: Number(form.get("capacity")), service_codes: form.getAll("service_codes"), active: form.get("active") === "on", reason: String(form.get("reason")).trim() }); if (result) { setTool(result); setDirty(false); data.reload(); } }}><div className="form-grid"><label>工具池名稱<input name="name" required maxLength={120} defaultValue={tool.name || ""} readOnly={!!tool.id} /></label><label>同時可用容量<input name="capacity" required type="number" min={1} max={100} step={1} defaultValue={tool.capacity || 1} /></label></div><label>允許服務（可多選）<select name="service_codes" required multiple size={7} defaultValue={tool.service_codes || []}>{services.map(service => <option key={service.code} value={service.code}>{service.name}</option>)}</select></label><label className="answer-option"><input type="checkbox" name="active" defaultChecked={tool.active !== false} />啟用此工具池</label><label>工具、授權數量與變更依據<textarea name="reason" required maxLength={1000} rows={3} /></label><Notice>名稱建立後固定。已有未來預留時，縮減容量、服務或停用會由後端拒絕，既有行程不會自動改寫。</Notice><button className="button" disabled={toolAction.pending}>確認儲存工具池版本</button>{conflict(toolAction, data.reload)}<MutationStatus action={toolAction} /></form>}
    </Card>
  </div></>;
}
