"use client";

import Link from "./guarded-link";
import { useEffect, useState, type FormEvent } from "react";
import { Award, BookOpen, CheckCircle2, Clock3 } from "lucide-react";
import { dateOnly, items, useMutation, useResource, type Row } from "@/lib/api";
import { Badge, ButtonLink, Card, Empty, ErrorState, Loading, MutationStatus, Notice, PageHeading, Status } from "./ui";
import { ResourcePanel } from "./customer";
import { AuthorizationSummary, trainingSources } from "./training-licenses";

export function LearnerHome() { return <><PageHeading eyebrow="YOUR PERSONAL LEARNING SPACE" title="我的學習" description="依照自己的步調學習，將資安觀念帶回每天的工作。" /><ResourcePanel path="/learner/enrollments">{data => items(data).length ? <div className="course-grid">{items(data).map(e => <Card key={e.id} title={e.course_title || e.title}><BookOpen size={30} color="#0f766e" /><p className="section-gap">{e.description || "閱讀章節、完成測驗，留下本次課程的學習紀錄。"}</p><div className="actions"><Status value={e.status} /><Badge>{e.cohort} 梯次</Badge><Badge>{trainingSources[e.authorization?.source || e.source] || "依核定授權"}</Badge></div><p className="form-help">授權期限：{dateOnly(e.expires_at)}（Asia/Taipei）</p><ButtonLink href={`/learn/courses/${e.id}`}>{e.status === "completed" ? "查看學習紀錄" : e.status === "assigned" ? "開始課程" : "繼續學習"}</ButtonLink>{e.certificate_id && <p className="section-gap"><Link className="text-link" href={`/learn/certificates/${e.certificate_id}`}><Award size={17} />查看完課證明</Link></p>}</Card>)}</div> : <Card><Empty title="目前沒有待修課程">企業訓練管理者派課後，您可以在這裡開始學習。</Empty></Card>}</ResourcePanel></>; }
export function LearnerCourse({ id }: { id: string }) { const resource = useResource(`/learner/enrollments/${id}`); const start = useMutation(); const [exam, setExam] = useState(false); if (resource.loading) return <Loading />; if (resource.error) return <ErrorState error={resource.error} retry={resource.reload} />; const data = resource.data!; return <><PageHeading eyebrow={`MY COURSE / ${data.cohort || ""}`} title={data.course_title || data.title || "我的課程"} description={`授權期限：${dateOnly(data.expires_at)}（Asia/Taipei）`} action={<Status value={data.status} />} />{data.authorization && <div className="section-gap"><AuthorizationSummary authorization={data.authorization} /></div>}<div className="tabs"><button className={!exam ? "active" : ""} onClick={() => setExam(false)}>章節學習</button><button className={exam ? "active" : ""} onClick={() => setExam(true)} disabled={["assigned", "reserved", "pending", "cancelled", "expired"].includes(data.status)}>課程測驗</button></div>{["assigned", "reserved", "pending"].includes(data.status) ? <Card title="準備開始學習"><div className="success-panel"><BookOpen size={42} /><h2>從今天的一個安全習慣開始。</h2><p>首次啟動會使用企業已預留的席次或點數，以下授權來源以後端核定為準。授權期限內續看不重複扣帳。</p><button className="button" disabled={start.pending} onClick={async () => { if (await start.mutate(`/learner/enrollments/${id}/start`)) resource.reload(); }}>確認開始課程</button><MutationStatus action={start} /></div></Card> : ["expired", "cancelled"].includes(data.status) ? <Card><Empty title="此課程授權已失效">請由企業訓練管理者確認適用的課程授權。</Empty></Card> : exam ? <Exam enrollment={data} onSuccess={resource.reload} /> : <LessonReader enrollment={data} onExam={() => setExam(true)} onProgress={resource.reload} />}{data.certificate_id && <Card title="已取得完課證明" className="section-gap"><div className="actions"><CheckCircle2 size={24} color="#0f766e" /><span>您已完成本次授權版本的教材與測驗。</span><ButtonLink href={`/learn/certificates/${data.certificate_id}`}>查看完課證明</ButtonLink></div></Card>}</>; }
function LessonReader({ enrollment, onExam, onProgress }: { enrollment: Row; onExam: () => void; onProgress: () => void }) {
  const resource = useResource(`/learner/enrollments/${enrollment.id}/lessons`);
  const [selected, setSelected] = useState(0); const [elapsed, setElapsed] = useState(0); const [running, setRunning] = useState(true); const action = useMutation();
  const lessons = items(resource.data).length ? items(resource.data) : items(enrollment.lessons); const lesson = lessons[selected];
  useEffect(() => { setElapsed(0); action.clear(); }, [selected]);
  useEffect(() => { if (!running) return; const interval = window.setInterval(() => { if (document.visibilityState === "visible") setElapsed(v => v + 1); }, 1000); return () => clearInterval(interval); }, [selected, running]);
  if (resource.error) return <ErrorState error={resource.error} retry={resource.reload} />;
  if (!lesson) return resource.loading ? <Loading /> : <Empty title="尚無可用章節">請由企業管理者確認教材版本與授權。</Empty>;
  const needed = Number(lesson.min_seconds || 20);
  return <div className="section-stack"><Card title="課程章節"><div className="tabs">{lessons.map((l, i) => <button className={selected === i ? "active" : ""} key={l.id} onClick={() => setSelected(i)}>0{i + 1} {l.title}</button>)}</div><span className="step-label">LESSON {selected + 1} / {lessons.length}</span><h2 className="section-gap">{lesson.title}</h2><div className="lesson-content">{lesson.content}</div><div className="actions"><Clock3 size={16} /><span className="form-help">本次閱讀 {elapsed} 秒 · 此章建議至少 {needed} 秒</span><button className="button button-secondary" onClick={() => setRunning(!running)}>{running ? "暫停閱讀計時" : "繼續閱讀"}</button></div><Notice>本課程為原創文字教材。伺服器驗證學習時間與測驗結果；正式影音服務尚未啟用，不顯示不可用播放器。</Notice><div className="actions"><button className="button" disabled={action.pending || elapsed < needed || !!action.result} onClick={async () => { const response = await action.mutate(`/learner/enrollments/${enrollment.id}/progress`, { lesson_id: lesson.id, seconds: Math.min(elapsed, needed) }); if (response) resource.reload(); }}>儲存本章閱讀進度</button>{selected < lessons.length - 1 ? <button className="button button-secondary" onClick={() => setSelected(selected + 1)}>下一章</button> : <button className="button button-secondary" onClick={onExam}>前往課程測驗</button>}</div><MutationStatus action={action} success="章節進度已由伺服器確認並儲存。" /><p className="form-help">教材與測驗各有完成條件。閱讀計時不是實務能力評量，完課亦不代表具備所有資安判斷能力。</p></Card></div>;
}
function Exam({ enrollment, onSuccess }: { enrollment: Row; onSuccess: () => void }) { const resource = useResource(`/learner/enrollments/${enrollment.id}/questions`); const action = useMutation(); const [answers, setAnswers] = useState<Record<string, number>>({}); const [confirm, setConfirm] = useState(false); if (resource.loading) return <Loading />; if (resource.error) return <ErrorState error={resource.error} retry={resource.reload} />; const questions = items(resource.data); async function submit(e: FormEvent) { e.preventDefault(); if (!confirm) { setConfirm(true); return; } const result = await action.mutate("/learner/attempts", { enrollment_id: enrollment.id, answers: questions.map(q => ({ question_id: q.id, choice: answers[q.id] })) }); if (result?.passed || result?.certificate_id) onSuccess(); }
  return <Card title="課程測驗"><Notice>伺服器會確認完整章節進度及剩餘測驗次數。{resource.data?.attempts_remaining !== undefined ? `剩餘 ${resource.data.attempts_remaining} 次。` : enrollment.attempts_remaining !== undefined ? `剩餘 ${enrollment.attempts_remaining} 次。` : "重考次數依課程版本限制。"}答案於授權範圍內依測驗結果提供說明。</Notice>{questions.length ? <form className="form-stack" onSubmit={submit}>{questions.map((q, i) => <fieldset key={q.id}><legend>{i + 1}. {q.prompt}</legend>{(q.choices as string[]).map((choice, n) => <label className="answer-option" key={`${q.id}-${n}`}><input type="radio" name={q.id} value={n} required checked={answers[q.id] === n} onChange={() => { setAnswers(a => ({ ...a, [q.id]: n })); setConfirm(false); }} />{choice}</label>)}</fieldset>)}{confirm && <div className="selection-summary"><strong>已完成 {Object.keys(answers).length} / {questions.length} 題</strong><span>確認送出將使用一次測驗機會，答案由伺服器評分。</span></div>}<button className="button" disabled={action.pending || !!action.result}>{action.pending ? "正在評分…" : confirm ? "確認送出測驗" : "檢查答案並送出"}</button><MutationStatus action={{ ...action, result: null }} />{action.result && <div className="selection-summary"><strong>{action.result.passed ? "本次測驗通過" : "本次尚未通過"}</strong><span>得分：{action.result.score_percent ?? action.result.score ?? "請見紀錄"}</span>{items(action.result.explanations).map((r, i) => <p key={i}>{r.explanation || r.text}</p>)}{action.result.certificate_id && <ButtonLink href={`/learn/certificates/${action.result.certificate_id}`}>查看完課證明</ButtonLink>}{!action.result.passed && <button className="button button-secondary section-gap" onClick={() => { action.clear(); setConfirm(false); resource.reload(); }}>依剩餘次數重新作答</button>}</div>}</form> : <Empty title="測驗尚未開放">請先完成章節學習，或確認課程授權版本。</Empty>}</Card>;
}
export function Certificate({ id }: { id: string }) { return <><PageHeading title="我的完課證明" description="證明本次課程與測驗已完成，不等同專業能力認證。" /><ResourcePanel path={`/learner/certificates/${id}`}>{data => <Card><div className="success-panel"><Award size={52} /><div className="eyebrow section-gap">CERTIFICATE OF COMPLETION</div><h1>課程完成證明</h1><p>{data.learner_name || data.name}</p><h2>{data.course_title || data.course?.title}</h2><p>課程版本：{data.course_version || data.version} · 梯次：{data.cohort}</p><p>完成日期：{dateOnly(data.issued_at || data.created_at)}（Asia/Taipei）</p><p className="mono">查驗碼：{data.verification_code || data.code || data.id}</p><Notice>本機原創示範課程的完成紀錄；不代表正式認證。證明查詢須維持授權，不公開多餘個資。</Notice><button className="button button-secondary" onClick={() => { const blob = new Blob([JSON.stringify({ certificate_id: data.id, course: data.course_title, version: data.course_version, cohort: data.cohort, issued_at: data.issued_at || data.created_at, verification_code: data.verification_code || data.code }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "kuanguard-course-certificate.json"; a.click(); URL.revokeObjectURL(url); }}>下載證明紀錄</button></div></Card>}</ResourcePanel></>; }
