"use client";

import Link from "./guarded-link";
import { useState, type ReactNode } from "react";
import { AlertCircle, ArrowRight, CheckCircle2, ChevronLeft, ChevronRight, Inbox, LoaderCircle, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { ApiError, type Row } from "@/lib/api";

export function Brand({ light = false }: { light?: boolean }) { return <Link className={`brand ${light ? "brand-light" : ""}`} href="/" aria-label="KUANGUARD 首頁"><span className="brand-mark"><ShieldCheck size={23} strokeWidth={1.8} /></span><span>KUANGUARD<small>企業資安服務平台</small></span></Link>; }
export function ButtonLink({ href, children, secondary = false, className = "" }: { href: string; children: ReactNode; secondary?: boolean; className?: string }) { return <Link className={`button ${secondary ? "button-secondary" : ""} ${className}`} href={href}>{children}<ArrowRight size={16} /></Link>; }
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: string }) { return <span className={`badge badge-${tone}`}>{children}</span>; }
const statuses: Record<string, string> = { draft: "草稿", pending: "待處理", reserved: "已預留", active: "有效", scheduled: "已排程", paused: "已暫停", cancelled: "已取消", completed: "已完成", published: "已發布", approved: "已核定", rejected: "未核定", failed: "失敗", processing: "處理中", ready: "就緒", preview: "待確認預覽", committed: "已匯入", accepted: "已確認接受", delivered: "已送達", unknown: "待對帳", unpaid: "待付款", paid: "已付款", sandbox: "開發測試", pending_activation: "待啟用", disabled: "未啟用", assigned: "待開始", in_progress: "進行中", passed: "通過", insufficient: "證據不足", not_tested: "未檢測", confirmed: "已確認", returned: "意見退回", partial: "部分驗收", awaiting_review: "待覆核", awaiting_verification: "待技術驗證", preparing: "待準備", observing: "觀測中", planned: "待寄送", queued: "已排入佇列", offered: "待確認報價", imported: "已匯入", invalid: "無有效資料", partial_success: "部分成功", adapter_disabled: "供應商未啟用", completed_sandbox: "Sandbox 已完成", manual_review: "待人工核對", local_private: "本機私有儲存", disconnected: "未連線", partial_refunded: "部分退款", payment_failed: "付款失敗", pending_review: "待覆核", pending_schedule: "待排程", open: "待處理", awaiting_payment: "待付款", cancelled_before_start: "啟動前取消", sent: "已寄送", expired: "已到期" };
export function Status({ value }: { value: unknown }) { const code = String(value || "pending"); return <Badge tone={["published", "approved", "completed", "passed", "paid", "active"].includes(code) ? "success" : ["failed", "rejected", "expired"].includes(code) ? "danger" : ["pending", "paused", "unknown", "insufficient", "pending_activation"].includes(code) ? "warning" : "neutral"}>{statuses[code] || code}</Badge>; }
export function Severity({ value }: { value: unknown }) { const key = String(value || "Unknown"); const labels: Record<string, string> = { Critical: "嚴重", High: "高風險", Medium: "中風險", Low: "低風險", Informational: "資訊", Unknown: "未分級" }; return <Badge tone={key.toLowerCase()}><AlertCircle size={12} />{labels[key] || key}</Badge>; }
export function Notice({ children, tone = "info" }: { children: ReactNode; tone?: string }) { return <div className={`notice notice-${tone}`}><AlertCircle size={18} /><div>{children}</div></div>; }
export function Loading() { return <div className="state-box" role="status"><LoaderCircle className="spin" size={26} /><strong>正在載入資料</strong><span>請稍候，正在確認您的存取權限。</span></div>; }
export function Empty({ title = "尚無資料", children }: { title?: string; children?: ReactNode }) { return <div className="state-box"><span className="state-icon"><Inbox size={27} /></span><strong>{title}</strong><span>{children || "相關資料建立後，會顯示在這裡。"}</span></div>; }
export function ErrorState({ error, retry }: { error: Error; retry?: () => void }) { const denied = error instanceof ApiError && error.status === 403; const expired = error instanceof ApiError && error.status === 401; return <div className="state-box error-state" role="alert"><AlertCircle size={28} /><strong>{denied ? "目前角色沒有存取權限" : expired ? "登入已到期" : "資料暫時無法載入"}</strong><span>{error.message}</span>{error instanceof ApiError && error.trace && <code>追查編號：{error.trace}</code>}{expired ? <ButtonLink href="/login">重新登入</ButtonLink> : retry && <button className="button button-secondary" onClick={retry}>重試</button>}</div>; }
export function MutationStatus({ action, success = "已完成，資料已儲存。" }: { action: { error: Error | null; result: Row | null }; success?: string }) { return <div aria-live="polite">{action.error && <Notice tone="danger">{action.error.message}{action.error instanceof ApiError && action.error.trace && <small>追查編號：{action.error.trace}</small>}</Notice>}{action.result && <div className="notice notice-success"><CheckCircle2 size={18} /><div>{success}{action.result.id && <small>紀錄編號：{action.result.id}</small>}</div></div>}</div>; }
export function PageHeading({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="page-heading"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div>; }
export function Card({ title, aside, children, className = "" }: { title?: string; aside?: ReactNode; children: ReactNode; className?: string }) { return <section className={`card ${className}`}>{title && <header className="card-header"><h2>{title}</h2>{aside}</header>}<div className="card-body">{children}</div></section>; }
export function Metric({ label, value, suffix, detail, href }: { label: string; value: ReactNode; suffix?: string; detail: string; href?: string }) { const inner = <><span className="metric-label">{label}</span><strong className="metric-value">{value}<small>{suffix}</small></strong><span className="metric-detail">{detail}{href && <ArrowRight size={14} />}</span></>; return href ? <Link href={href} className="metric">{inner}</Link> : <div className="metric">{inner}</div>; }
export type Column = { key: string; title: string; render?: (row: Row) => ReactNode };
export function DataTable({ rows, columns, title = "資料列表", onPage, page = 1, total, pageSize = 20 }: { rows: Row[]; columns: Column[]; title?: string; onPage?: (page: number) => void; page?: number; total?: number; pageSize?: number }) {
  const [query, setQuery] = useState(""); const [hidden, setHidden] = useState<string[]>([]);
  const shown = columns.filter(c => !hidden.includes(c.key));
  const filtered = rows.filter(r => columns.some(c => typeof r[c.key] !== "object" && String(r[c.key] ?? "").toLowerCase().includes(query.toLowerCase())));
  return <div className="data-table"><div className="table-toolbar"><label className="search-field"><Search size={16} /><input aria-label={`搜尋${title}（目前頁面）`} placeholder="搜尋目前頁面…" value={query} onChange={e => setQuery(e.target.value)} /></label><details className="column-picker"><summary><SlidersHorizontal size={16} />顯示欄位</summary><div>{columns.map(c => <label key={c.key}><input type="checkbox" checked={!hidden.includes(c.key)} disabled={!hidden.includes(c.key) && shown.length === 1} onChange={() => setHidden(h => h.includes(c.key) ? h.filter(k => k !== c.key) : [...h, c.key])} />{c.title}</label>)}</div></details></div>{!filtered.length ? <Empty title={query ? "沒有符合的資料" : "尚無資料"}>{query ? "請調整搜尋文字；搜尋範圍是目前頁面。" : undefined}</Empty> : <div className="table-scroll" tabIndex={0} aria-label={`${title}，可水平捲動`}><table><caption className="sr-only">{title}，目前第 {page} 頁</caption><thead><tr>{shown.map(c => <th key={c.key} scope="col">{c.title}</th>)}</tr></thead><tbody>{filtered.map((row, i) => <tr key={String(row.id || i)}>{shown.map(c => <td key={c.key}>{c.render ? c.render(row) : String(row[c.key] ?? "—")}</td>)}</tr>)}</tbody></table></div>}<div className="table-footer"><span>本頁 {filtered.length} 筆{total !== undefined && ` · 共 ${total} 筆`}{query && " · 已套用本頁搜尋"}</span>{onPage && <div className="pagination"><button className="icon-button" aria-label="上一頁" disabled={page <= 1} onClick={() => onPage(page - 1)}><ChevronLeft size={16} /></button><span>第 {page} 頁</span><button className="icon-button" aria-label="下一頁" disabled={total !== undefined ? page * pageSize >= total : rows.length < pageSize} onClick={() => onPage(page + 1)}><ChevronRight size={16} /></button></div>}</div></div>;
}
